# _config.yml
title: "odeh.page"
description: ""
url: ""
baseurl: ""
theme: null
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - .htaccess
  - _pages
